# Generated by Django 4.1.1 on 2023-03-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
