# Generated by Django 4.1.1 on 2023-04-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_student_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course", name="end_time", field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="course", name="start_time", field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="course", name="duration", field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(name="CourseSchedule",),
    ]
