# Generated by Django 4.1.1 on 2023-04-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_course_end_time_alter_course_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="end_time", field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="course", name="start_time", field=models.TimeField(null=True),
        ),
    ]
